### ISSUE TITLE
[BUG ?] Theoretical BPP > Empirical BPP for mbt2018-mean

### ISSUE THREAD

**Issue by YannDubs** [InterDigitalInc/CompressAI#12]
Hi! 

When running the [comparison](https://github.com/InterDigitalInc/CompressAI/blob/master/examples/CompressAI%20Models%20Comparison%20Demo.ipynb) notebook, I tried also computing the **real** BPP (instead of only the theoretical one), for every model it was quite close to the theoretical one (slightly larger which makes sense), but for mbt2018-mean the **theoretical** BPP is larger than the empirical one, which I don't think should be possible.

Here's the few lines of code I added, as well as the surprising result (in red) 

<img width="853" alt="Screenshot 2020-12-03 at 23 26 52" src="https://user-images.githubusercontent.com/24327668/101111312-34825a00-35db-11eb-937f-0be5d9f244b4.png">

I looked at the code and it seems that `MeanScaleHyperprior` does not take absolute values of `y` (i.e. both in `compression` and `forward` you have `z = self.h_a(y)`), but `ScaleHyperprior` does (i.e. `z = self.h_a(torch.abs(y))`). Could that be the reason ? I thought that the only difference between `MeanScaleHyperprior` and `ScaleHyperprior` was that one predicted the mean of the gaussian and the other didn't.

Thanks for the library 💯

**Comment by jbegaint** [comment]
Hi Yann,

thanks for the feedback! How many images are you using?

The models do not return the theoretical likelihoods but the estimated ones (from learned parameters), so the actual entropy would be a bit off. Also, the entropy coder for the hyperpior-based models does not directly use the predicted scales to derive the CDFs but the closest ones in a fixed `scale_table` [1], which can also provides some variations in the actual bpp after encoding. It's possible the "quantized" scales in that specific case are more efficient compression-wise than the "unquantized" predicted ones.

For the `MeanScaleHyperprior` architecture we follow the original paper from Minnen et al. (https://arxiv.org/abs/1809.02736), which does not use an `abs()`, contrary to the original `ScaleHyperprior` model from Ballé et al. (https://arxiv.org/abs/1802.01436). In the `ScaleHyperpior` case, the hyperprior is only used to predict the scale/magnitude of the latent Gaussian mixture, I guess that's why the authors originally applied `abs()` on the latent element before the hyperprior synthesis.

[1]: so that the CDFs can be pre-computed, see https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/entropy_models/entropy_models.py#L586 and https://github.com/InterDigitalInc/CompressAI/blob/master/compressai/models/priors.py#L195

**Comment by YannDubs** [comment]
Hi Jean,

Thanks for the detailed answer. I was only using the single image that you load in that notebook.

What I meant by "theoretical BPP" was not the theoretical log likelihood of the image (which of course we do not have access to), but the estimated log likelihood which from what I understand is a (tight) lower bound on the BPP necessary for entropy coding the image using the learned entropy model. That being said your explanation about `scale table` might explain the small variance, I'd have to test it on more images to make sure. 

Thanks, I'll close it for now and will reopen if I investigate it further.

BTW I think it would be nice to actually provide the real BPP in a few of your experiments / notebooks

**Comment by jbegaint** [comment]
Hi Yann, thanks for the feedback! I'll try to update the notebooks soon.
