### ISSUE TITLE
Issue with Using CheckerboardMaskedConv2d from layer.py

### ISSUE THREAD

**Issue by formioq** [InterDigitalInc/CompressAI#291]
In the process of training using **mbt2018** as the base model, I attempted to replace the original **MaskedConv2d** with **CheckerboardMaskedConv2d** (mask_type=B) as the context model. During testing, I noticed that while the PSNR increased to 33 (at epoch=100), the bpp dropped to 0.13 (in fact, from the first epoch, the bpp was around 0.2, and I set lambda=0.01). Such high results are clearly abnormal. I want to know if there are any issues with directly replacing the usage. Please tell me where the problem lies or if there is any solution.
<img width="653" alt="4" src="https://github.com/InterDigitalInc/CompressAI/assets/170353368/41fcc6f0-ee59-41e2-a36d-a558ec4d717e">
<img width="656" alt="3" src="https://github.com/InterDigitalInc/CompressAI/assets/170353368/6d184de9-52e2-4916-9eb4-d4cbc3fd0b77">

**Comment by YodaEmbedding** [comment]
This usually occurs when some of the likelihood terms are missing during the bpp_loss computation.

Similarly, during model eval, the bpp should measure the length of all the bytestrings. If that one is also too small, it might be because it's measuring the length of the keys or list length.

One way around both of these is to recursively flatten out the likelihoods/bytestrings. I might look into introducing a PR on this so this bug becomes less likely.
