### ISSUE TITLE
cannot import compressai._CXX

### ISSUE THREAD

**Issue by GongsunBABA** [InterDigitalInc/CompressAI#304]
## Bug

I have followed the procedure to install compressai, updated the CXX toolchain, and reinstalled compressai, but the issue with importing compressai.CXX still persists. 

like this：
![DE@`3N(9ZN35AI3G(` A)L4](https://github.com/user-attachments/assets/527e9c06-9735-4cb0-9251-b4f4fcc631b0)

**Comment by YodaEmbedding** [comment]
1. What happens when you run `python -c 'import compressai'` within the virtual environment?
2. The screenshot shows that VSCode is using a python interpreter which can't find `compressai._CXX`. Ensure that the correct interpreter/environment is selected: https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment
