### ISSUE TITLE
About evaluation 

### ISSUE THREAD

**Issue by MarineCao** [InterDigitalInc/CompressAI#54]
Hello,
At first, thanks for your work!

I have trained the `ScaleHyperprior` model with my dataset, and I'm trying to use inference() to evaluate my checkpoint with my dataset, but several images' PSNR are NaN(1~4 in 24 test images) and it appeared randomly. Everytime I run my evaluation code, the images with NaN PSNR are different and the other images‘ PSNR are right. I have checked the decompressed images with NaN PSNR, and there are many block mosaics and serious artifact in these images. However, the results of inference_entropy_estimation() are all right. I'm not sure whether my evaluation code is correct, my code is as follows(the `ScaleHyperprior(128, 192)` is the same to the source code):

`net = ScaleHyperprior(128, 192)`
`net = net.from_state_dict(torch.load(checkpoint_path)["state_dict"])`
`net.update(force=True)`
`net= net.eval().cuda()`

After these steps, I fed the test images and the `net` into `inference()` to get bpp and PSNR.

So what's wrong with this? Is this a bug or my code is wrong?

I use compressai 1.1.4.
Thanks!

**Comment by jbegaint** [comment]
Hi, can you try setting `torch.backends.cudnn.deterministic = True` in your main script?

They were some updates in pytorch 1.8 that produces undeterministic behavior in the convolution. Usually the NaN are caused by the hyperprior decoding, the scales prediction need to be 100% reproducible otherwise the entropy decoding fails to decode the correct latent values.

A better solution would be to have a quantized hyperprior decoder for the scales. We'll release a model soon.

**Comment by MarineCao** [comment]
Thanks for your reply!
I set `torch.backends.cudnn.deterministic = True`, and it works. 
Thanks!
